# Change this for production deployment or override this with -Dspring.profiles.active=prod
# Available profiles: dev, test, prod
spring.profiles.active=prod
# Application name
application.name=cumulocity-maintenance-module

# Server configuration
server.port=8080

spring.ai.openai.chat.options.model=gpt-4
spring.ai.openai.chat.options.temperature=0.7