# Application name
application.name=cumulocity-maintenance-module

# Microservice settings
microservice.subscription.enabled=false

# Disable Spring Security for tests
spring.security.enabled=false
management.security.enabled=false