#spring:
#  ai:
#    openai:
#      api-key: test-key-for-testing
#
#application:
#  name: cumulocity-maintenance-module
#
#C8Y:
#  bootstrap:
#    register: false
#  microservice:
#    isolation: MULTI_TENANT
#  baseURL: https://ws-onboarding-av.eu-latest.cumulocity.com
#  tenant: t2103204464
#  user: akshay.vastrad@cumulocity.com
#  password: Ka25ew9165$